### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [joseahr/informaTorrent-Node.JS#1]
you can easily place all this SQL: https://github.com/joseahr/informaTorrent-Node.JS/blob/master/app/controllers/queries.js

Into external SQL files. See this demo: https://github.com/vitaly-t/pg-promise-demo

Specifically, how SQL is organized and loaded: https://github.com/vitaly-t/pg-promise-demo/tree/master/db/sql

It is done with the help of QueryFile: http://vitaly-t.github.io/pg-promise/QueryFile.html

**Comment by joseahr** [comment]
Done. Thanks for your awesome lib!
